import React, { useState, useEffect } from "react";
import Head from "next/head";
import Link from "next/link";
import { useUser } from "@auth0/nextjs-auth0/client";
import styles from "@/styles/Home.module.css";

import { callPrivate, callPublic, callRBAC } from "../utils/api";

export default function Home() {
  const [publicResponse, setPublicResponse] = useState(null);
  const [privateResponse, setPrivateResponse] = useState(null);
  const [RBACResponse, setRBACResponse] = useState(null);
  const { user, error, isLoading } = useUser();

  useEffect(() => {
    (async () => {
      const p = await callPublic();
      setPublicResponse(p.message);

      const pr = await callPrivate();
      setPrivateResponse(pr.message);

      const rb = await callRBAC();
      setRBACResponse(rb.message);
    })();
  }, []);

  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>{error.message}</div>;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav className={styles.nav}>
          <Link href="/private">Go to private page</Link>
        </nav>
      </header>
      <main className={styles.main}>
        {user && (
          <div>
            <img src={user.picture} alt={user.name} />
            <h2>{user.name}</h2>
            <p>{user.email}</p>
          </div>
        )}
        <section className={styles.description}>
          <h1 className={styles.heading}>Homepage</h1>
          <p>Public API Response: {publicResponse}</p>
          <p>Private API Response: {privateResponse}</p>
          <p>RBAC API Response: {RBACResponse}</p>
          <a href="/api/auth/login" className="button">
            Login
          </a>
          {user && (
            <a href="/api/auth/logout" className="button">
              Logout
            </a>
          )}
        </section>
      </main>
    </>
  );
}