import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { withPageAuthRequired } from '@auth0/nextjs-auth0';
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })

export default function Private() {
  return (
    <>
      <Head>
        <title>Private Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1>Private Page</h1>
          <Link href="/">Go to back home page</Link>
        </div>
      </main>
    </>
  )
}

export const getServerSideProps = withPageAuthRequired();